CREATE TABLE [dbo].[TBALTERNATIVA] (
    [NUMERO]         INT           IDENTITY (100, 1) NOT NULL,
    [QUESTAO_NUMERO] INT           NOT NULL,
    [DESCRICAO]      VARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_QUESTAO] FOREIGN KEY ([QUESTAO_NUMERO]) REFERENCES [dbo].[TBQUESTAO] ([NUMERO])
);

