CREATE TABLE [dbo].[TBQUESTAO] (
    [NUMERO]         INT            IDENTITY (100, 1) NOT NULL,
    [MATERIA_NUMERO] INT            NOT NULL,
    [BIMESTRE]       VARCHAR (50)   NULL,
    [PERGUNTA]       VARCHAR (1000) NOT NULL,
    [RESPOSTA]       VARCHAR (1000) NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_MATERIA] FOREIGN KEY ([MATERIA_NUMERO]) REFERENCES [dbo].[TBMATERIA] ([NUMERO])
);

