CREATE TABLE [dbo].[TBTESTE] (
    [NUMERO]            INT           IDENTITY (100, 1) NOT NULL,
    [PROVA]             VARCHAR (MAX) NOT NULL,
    [NUMEROQUESTOES]    VARCHAR (10)  NOT NULL,
    [GABARITO]          VARCHAR (900) NULL,
    [DATA]              DATETIME      NULL,
    [DISCIPLINA_NUMERO] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_DISCIPLINAS_TESTE] FOREIGN KEY ([DISCIPLINA_NUMERO]) REFERENCES [dbo].[TBDISCIPLINA] ([NUMERO])
);

